version: "3"
services:
  app:
    container_name: studentadmin-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8080:8080"
    env_file:
      - .env
