name: CI Build Test

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.21.3"

      - name: Install Go dependencies
        working-directory: .
        run: go mod tidy && go mod download

      - name: Run Go tests
        working-directory: .
        run: go test ./...
